import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aeonikMono = localFont({
  src: [
    {
      path: "../public/fonts/aeonik_mono_pro/aeonikmonopro-light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-aeonik-mono",
  display: "swap",
});

const diatype = localFont({
  src: [
    {
      path: "../public/fonts/diatype_cyrillic/ABCDiatypeCyrillic-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/diatype_cyrillic/ABCDiatypeCyrillic-LightItalic.woff2",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-diatype",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${aeonikMono.variable} ${diatype.variable} h-full antialiased overscroll-none`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
